//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Игра
    {
        public string ID_пользователя { get; set; }
        public string время { get; set; }
        public string Дата { get; set; }
        public string Время_игры { get; set; }
        public string Количество_монет { get; set; }
    
        public virtual Игроки Игроки { get; set; }
    }
}
